app_profile/urls.py
from django.conf.urls import url
from django.urls import include
from .views import index

app_name = 'app_profile'

urlpatterns = [
    url(r'^$', index, name='profile'),
]

landing_page/urls.py
from django.urls import path
from landing_page.views import *

urlpatterns = [
    path('', index, name='landing_page'),
    path('logout', logout, name = "logout"),
]

news/urls.py
from django.urls import path
from django.conf.urls import url
from news.views import *

urlpatterns = [
    path('', index_news, name='news'),
    url(r'^(?P<value>\d+)/$', show_news, name='show_news'),
]

programs/urls.py
from django.conf.urls import url
from django.urls import include
from .views import index, show_details
import donation_form.urls as donation_form

app_name = 'programs'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<value>\d+)/', show_details, name='details'),
]

tugas_1/urls.py
from django.contrib import admin
from django.urls import path, include
import landing_page.urls as landing_page
import programs.urls as programs
from donation_form.views import make_donation
import registration.urls as registration
import donation_form.urls as donation_form
import app_profile.urls as profile
import app_testimoni.urls as app_testimoni

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(landing_page)),
    path('news/', include('news.urls')),
    path('program/', include(programs)),
    path('registration/', include(registration)),
    path('make_donation/', include(donation_form)),
    path('profile/', include(profile)),
    path('about-us/', include(app_testimoni)),
]

landing_page/models.py
from django.db import models

# Create your models here.

landing_page/views.py
from django.shortcuts import render
from django.contrib.auth import logout as auth_logout
from django.http import HttpResponseRedirect

# Create your views here.
response = {}

def logout(request):
    """Logs out user"""
    auth_logout(request)
    return HttpResponseRedirect('/')

def index(request):
    return render(request, 'landing_page.html', response)

landing_page/templates/footer.html
<div class="footer-pink py-3">
    <div class="container">
        <p>Kontak kami:</p>
        <div class="row justify-content-center">
            <div class="mx-1">
                <img src="https://cdn4.iconfinder.com/data/icons/social-media-icons-the-circle-set/48/facebook_circle-512.png" style="width:30px">
            </div>
            <div class="mx-1">
                <img src="http://icons-for-free.com/free-icons/png/512/294709.png" style="width:30px">
            </div>
            <div class="mx-1">
                <img src="https://instagram-brand.com/wp-content/themes/ig-branding/assets/images/ig-logo-email.png" style="width:30px">
            </div>
        </div>
    </div>
    </div>
</div>

landing_page/templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'tugas_1.css' %}">
  <title>{% block title %}Dare2Care - A Crowd Funding Site{% endblock %}</title>
</head>

<body style="background-image: url({% static 'tsunami.jpg' %})">
{% include 'navbar.html' %}
{% block navbar %}
{% endblock %}

  <div class="text-center outer-div">
      <div class="mx-auto inner-div bg-container py-4">
        <div class="h1 text-pink">Selama kamu masih berdiri, cobalah untuk ulurkan tangan kepada orang-orang yang sedang jatuh</div>
        <a href="{% url 'programs:index' %}" class="btn btn-pink mt-4" role="button">Dare to Care</a>
      </div>
  </div>

</body>
</html>

landing_page/templates/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark navbar-color">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="container">
		<a class="navbar-brand" href="/">Dare2Care</a>
		<div style="width:100%">
			<div class="float-right">
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav">
						{% if user.is_authenticated %}
                            <a class="nav-item nav-link active" href="{% url 'app_profile:profile' %}"><span class="mr-2">Halo, <b>{{ user.username }}</b></span> | </a>
                        {% endif %}
						<a class="nav-item nav-link active" href="{% url 'landing_page'%}">Beranda<span class="sr-only">(current)</span></a>
						<a class="nav-item nav-link active" href="{% url 'news'%}">Berita</a>
						<a class="nav-item nav-link active" href="{% url 'programs:index' %}">Program</a>
						<a class="nav-item nav-link active" href="/about-us/">Tentang Kami</a>
						{% if user.is_authenticated %}
                            <a class="nav-item nav-link active" href="{% url 'logout'%}">Keluar</a>
                        {% else %}
                            <a class="nav-item nav-link active" href="{% url 'social:begin' 'google-oauth2' %}">Daftar/Masuk</a>
                        {% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</nav>